// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI07CZ060WhaJ28Ri_Yb4OqkCJrKJqE9s',
    appId: '1:801650933959:web:f74c448243d1b4b460bee2',
    messagingSenderId: '801650933959',
    projectId: 'flutter-quiz-302d1',
    authDomain: 'flutter-quiz-302d1.firebaseapp.com',
    databaseURL: 'https://flutter-quiz-302d1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-302d1.appspot.com',
    measurementId: 'G-EMZK3KY09X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Evpwt3HKJYDolYOK5Cik7XTIr-Cfi-Q',
    appId: '1:801650933959:android:08616433af50f59860bee2',
    messagingSenderId: '801650933959',
    projectId: 'flutter-quiz-302d1',
    databaseURL: 'https://flutter-quiz-302d1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-302d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1rGVm4zyEPStqhqCRa56W8Nt5kZaXYY',
    appId: '1:801650933959:ios:635bc0ef070f79c560bee2',
    messagingSenderId: '801650933959',
    projectId: 'flutter-quiz-302d1',
    databaseURL: 'https://flutter-quiz-302d1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-302d1.appspot.com',
    iosClientId: '801650933959-p3r8afsnntusih53t3mno66qjpoaa45a.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentsQuiz',
  );
}
